### ISSUE TITLE
Readme feature claim is a little misleading

### ISSUE THREAD

**Issue by FoamyGuy** [Corgea/retriever#2]
This is a interesting and clever idea for sharing secrets. Thank you for publishing it and setting up a demo instance for people to try.

In the list of features visible in the readme it says "No data is sent to a server".

However in the instance of this page hosted at `https://retriever.corgea.io/` it is actually sending data to a server including "fingerprint" information about the browser viewing the page and a distinct device ID. 

![image](https://github.com/Corgea/retriever/assets/2406189/c02bc161-02ab-4474-a051-87c6a573284a)

The data in this POST request contains URL encoded JSON including: OS, Browser, browser versions, screen size, and distinct device ID. 

In the code here it checks the host and initializes the mixpanel tracking: https://github.com/Corgea/retriever/blob/a89741b0f608143ab6423039e446084296e638da/index.html#L22-L24 So it is clear that as written it will only activate for your demo instance of the tool.

I understand that this sort of tracking and analytics is common across the web, and I can see why you'd want that information for the instance of this tool that your hosting as a demo inside of Github. I do not feel there is inherently anything bad or wrong about the inclusion of this functionality.

But honestly It's a little off-putting that this is occurring when the project readme states plainly "No data is sent to a server".

It would be more truthful to rephrase that feature to "Your secrets and the private keys that encrypt them are never sent to a server by retriever"

I believe it would also be best to state explicitly within the readme that the demo instance of the tool does include an analytics tracker that sends data to a server, and in the interest of transparency I believe it would be good to state explicitly what information it does collect even if this information is routinely collecting by similar web analytics and tracking utilities.

**Comment by asadeddin** [comment]
Hi!

Thanks for being patient, and apologies for taking too long to respond. We totally missed this. We'll monitor the project more actively moving forward.

I totally understand why this is off-putting and you're absolutely correct. We should clarify this more. We use Mixpanel to see if the site is getting traffic, and like you said, we don't get any of the secrets, or keys. 

You're also correct that it's only if it's hosted by us, and if you run this locally or on your own instance then we don't get any analytics. Additionally, folks can remove this if they want to. 

I'll update our readme to include all of this. Thanks for being a good custodian of security and privacy. We really appreciate your PR's, and reporting this issue.

**Comment by asadeddin** [comment]
Fixed issue with commit: https://github.com/Corgea/retriever/commit/023c4edeb3ca33db38de74d34016a6fc0fe525e7
